[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
heapless = "0.7"
itertools = { version = "0.10", default-features = false }
libc-print = "0.1"

[dev-dependencies]
assert_cmd = "2"
paste = "1"
